### ISSUE TITLE
Creation de compte avec un Nom de moins de 8 charactères

### ISSUE THREAD

**Issue by guigur** [ecoticket/ecoticket-web#1]
lors d'une inscription, si le pseudo est de moins de 8 caractères  impossible de s'inscrire avec le message "Le mot de passe doit contenir au moins 8 caractères." 
![mot de passe](https://cloud.githubusercontent.com/assets/1360703/19908045/c708adc8-a081-11e6-9f73-386192beb8d8.PNG)

**Comment by audiogenic** [comment]
done
