### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by guigur** [ecoticket/ecoticket-web#2]
ça serais bien de mettre un footer avec une phrase du genre "Ecoticet &copy 2016" jutes en gris ou en vert pomme

**Comment by audiogenic** [comment]
done commit dd5bab1ada32cf7e8ee5fbdb63577126a9aa3136

**Comment by audiogenic** [comment]
c'etait moche centré avec la page et sticky ou centré avec le contenu et pas sticky pas compatible ac MDL a voir pour une prochaine grosse maj graphique
