### ISSUE TITLE
margin top card paramètres

### ISSUE THREAD

**Issue by guigur** [ecoticket/ecoticket-web#5]
Il devrais y avoir quelques pixel d'écart entre le header et la card des paramètres 
![eco card](https://cloud.githubusercontent.com/assets/1360703/19912123/915c9e8e-a098-11e6-9ce7-aaabf3d31a57.PNG)

**Comment by guigur** [comment]
c'est le cas avec toutes les cards en fait (comme créer un groupe)

**Comment by audiogenic** [comment]
Je trouve jolie la superposition header / body et je vois pas la diff avec la creation de groupe :/

**Comment by guigur** [comment]
bah la card est quasis collée avec le header, ca serais mieux (en tout cas je pense que 20 pixels de margin ça ferais plus propre.
