### ISSUE TITLE
Fautes

### ISSUE THREAD

**Issue by guigur** [ecoticket/ecoticket-web#6]
Créer ![eco cree](https://cloud.githubusercontent.com/assets/1360703/19912190/11d7f6b2-a099-11e6-9756-0120b1634c40.PNG)

**Comment by guigur** [comment]
Déconnexion ![eco deco](https://cloud.githubusercontent.com/assets/1360703/19912344/173cc19a-a09a-11e6-9211-05bcb867aa7c.PNG)

**Comment by guigur** [comment]
Mes tickets (pas de majuscule au deuxième t)

**Comment by audiogenic** [comment]
done
